# Generated by Django 5.2.5 on 2025-08-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', 'default_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dds',
            name='test',
        ),
        migrations.AddField(
            model_name='dds',
            name='commentary',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='dds',
            name='summ',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='writecategory',
            name='parent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DDS.writetype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dds',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDS.writecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dds',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDS.writesubcategory', verbose_name='Подкатегория'),
        ),
    ]
