# Generated by Django 5.2.5 on 2025-08-14 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriteCategory',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WriteStatus',
            fields=[
                ('status', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус сделки',
                'verbose_name_plural': 'Статусы сделки',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='WriteType',
            fields=[
                ('write_type', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип сделки',
                'verbose_name_plural': 'Типы сделок',
                'ordering': ['write_type'],
            },
        ),
        migrations.CreateModel(
            name='WriteSubcategory',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Название подкатегории')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDS.writecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DDS',
            fields=[
                ('write_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный номер записи')),
                ('write_date', models.DateField(auto_now=True, verbose_name='Дата создания записи')),
                ('test', models.TextField(choices=[('Audio', [('vinyl', 'Vinyl'), ('cd', 'CD')]), ('Video', [('vhs', 'VHS Tape'), ('dvd', 'DVD')]), ('unknown', 'Unknown')], null=True, verbose_name='Тестирование групп')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DDS.writecategory', verbose_name='Категория')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDS.writestatus', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DDS.writesubcategory', verbose_name='Подкатегория')),
                ('write_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDS.writetype', verbose_name='Тип')),
            ],
        ),
    ]
