# Generated by Django 5.2.5 on 2025-08-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0001_remove_dds_test_dds_commentary_dds_summ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writecategory',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DDS.writetype', verbose_name='Тип'),
        ),
    ]
