# Generated by Django 5.2.5 on 2025-08-16 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0002_alter_writecategory_parent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='write_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата создания записи'),
        ),
    ]
