# Generated by Django 5.2.5 on 2025-08-14 10:29

from django.db import migrations

def enter_default_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    WriteStatus = apps.get_model("DDS", "WriteStatus")
    WriteType = apps.get_model("DDS", "WriteType")
    
    write_status_new_rows = [
        WriteStatus(status="Бизнес"),
        WriteStatus(status="Личное"),
        WriteStatus(status="Налог")
    ]
    
    write_type_new_rows = [
        WriteType(write_type="Пополнение"),
        WriteType(write_type="Списание")
    ]
    
    for row in write_status_new_rows:
        row.save()
        
    for row in write_type_new_rows:
        row.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DDS', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(enter_default_data)
    ]
